import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.css';
import AppThemeProvider from "./components/AppThemeProvider";
import Nav from "./components/navbar/Nav";
import ReduxProvider from "./components/ReduxProvider";
import Footer from "./components/footer/Footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Hotelapp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
        <AppThemeProvider>
        <Nav/>{children}<Footer/></AppThemeProvider>
        </ReduxProvider></body>
    </html>
  );
}
